name = "expensify-backup"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "expensify-backup"
database_id = "d6602972-cfc9-4620-8547-0947a2030da5"

[[r2_buckets]]
binding = "RECEIPTS"
bucket_name = "expensify-receipts"
